[package.mg-ddm-gz]
service_name = "mg-ddm"
source.type = "local"
source.rust.binary_names = ["ddmd", "ddmadm"]
source.rust.release = true
source.paths = [
  { from = "smf", to = "pkg" }
]
output.type = "tarball"

[package.mg-ddm]
service_name = "mg-ddm"
source.type = "local"
source.rust.binary_names = ["ddmd", "ddmadm"]
source.rust.release = true
source.paths = [
  { from = "smf/ddm_method_script.sh", to = "/opt/oxide/mg-ddm/pkg/ddm_method_script.sh" },
  { from = "smf/refresh_ctrun_child.sh", to = "/opt/oxide/mg-ddm/pkg/refresh_ctrun_child.sh" },
  { from = "smf/ddm/manifest.xml", to = "/var/svc/manifest/site/mg-ddm/manifest.xml" }
]
output.type = "zone"

[package.mgd]
service_name = "mgd"
source.type = "local"
source.rust.binary_names = ["mgd", "mgadm"]
source.rust.release = true
source.paths = [
  { from = "smf/mgd_method_script.sh", to = "/opt/oxide/mgd/pkg/mgd_method_script.sh" },
  { from = "smf/refresh_ctrun_child.sh", to = "/opt/oxide/mgd/pkg/refresh_ctrun_child.sh" },
  { from = "smf/mgd/manifest.xml", to = "/var/svc/manifest/site/mgd/manifest.xml" }
]
output.type = "zone"
